########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.svg"
# meta data
author: "Osanda Lelum"
description: "This is meta description"
# google analitycs ID
google_analitycs_id: "" # your id
# contact form action
contact_form_action: "#" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2023 Designed and Developed by [OsandaLelum](https://osandalelum.github.io/)"

# preloader
preloader:
  enable: true
  preloader: "/assets/images/pre.gif" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:
  - name: "facebook"
    icon: "ti-facebook" # themify icon pack https://themify.me/themify-icons
    link: "https://www.facebook.com/osanda.lelum/"

  - name: "twitter"
    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link: "https://twitter.com/OsandaLelum"

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/OsandaLelum"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "https://www.linkedin.com/in/osanda-lelum/"
